Repository UPE-FIU/Waves, pull requests merged in 2019-08, with the labels that each got.

#7 Schedule Buttons update
  package-lock.json
  package.json
  src/config/data/schedule.json
  src/pages/landing/schedule/index.jsx
  src/pages/landing/schedule/styles.css
  src/pages/landing/styles.css
  yarn.lock
Labels: enhancement

#11 Fix conflict
  src/assets/animals/Submarine.svg
  src/assets/waves/Asset 23.svg
  src/assets/waves/Asset 25.svg
  src/assets/waves/Background_Sand.svg
  src/assets/waves/beach.svg
  src/assets/waves/locationinfo.svg
  src/assets/waves/sponsor.svg
  src/assets/waves/spotify.svg
  src/assets/waves/surfboard-full.svg
  src/assets/waves/surfboard.svg
  src/assets/waves/twitter.svg
  src/assets/waves/upe.svg
  src/config/data/sponsors.json
  src/pages/landing/faqs/index.jsx
  src/pages/landing/faqs/styles.css
  src/pages/landing/tracks/index.jsx
  src/pages/landing/tracks/styles.css
Labels: bug

#12 added FAQ icons
  src/components/card/index.jsx
Labels: enhancement

#13 added sea floor, schedule, manatee, etc.
  src/assets/animals/Manatee.svg
  src/assets/theme/footer/footerBackground.svg
  src/components/footer/index.jsx
  src/components/footer/styles.css
  src/config/data/schedule.json
  src/pages/landing/schedule/index.jsx
  src/pages/landing/schedule/styles.css
  src/pages/landing/tracks/index.jsx
  src/pages/landing/tracks/styles.css
Labels: enhancement

#17 added faq icons
  src/components/card/styles.css
  src/pages/landing/main/styles.css
  src/pages/landing/supporters/styles.css
Labels: enhancement

#18 Added manatee and animations
  src/assets/animals/Manatee.svg
  src/pages/landing/schedule/styles.css
Labels: enhancement

#19 Jehf animation update
  src/assets/theme/footer/f.svg
  src/assets/theme/footer/footerBackground.svg
  src/assets/waves/angler_fish.svg
  src/assets/waves/scuba_diver.svg
  src/assets/waves/small_rocks.svg
  src/assets/waves/starfish.svg
  src/assets/waves/surfboard.svg
  src/components/animatedWaves/styles.css
  src/components/footer/index.jsx
  src/components/footer/styles.css
  src/components/trackItem/styles.css
  src/css/App.css
  src/pages/landing/faqs/index.jsx
  src/pages/landing/info/index.jsx
  src/pages/landing/main/index.jsx
  src/pages/landing/main/styles.css
  src/pages/landing/organizers/index.jsx
  src/pages/landing/organizers/styles.css
  src/pages/landing/schedule/index.jsx
  src/pages/landing/schedule/styles.css
  src/pages/landing/supporters/index.jsx
  src/pages/landing/supporters/styles.css
  src/pages/landing/tracks/index.jsx
  src/pages/landing/tracks/styles.css
  yarn.lock
Labels: deploy

#25 made changes to overflow
  src/components/scrollMenu/styles.css
  src/css/App.css
  src/css/index.css
  src/pages/landing/index.jsx
  src/pages/landing/styles.css
Labels: bug

#32 Jehf fixes
  public/index.html
  src/components/trackItem/index.jsx
  src/components/trackItem/styles.css
  src/pages/landing/supporters/index.jsx
  src/pages/landing/supporters/styles.css
Labels: enhancement

#34 added wave 2 sponsors
  src/assets/logos/sponsors/Chevron.svg
  src/assets/logos/sponsors/Dell.svg
  src/assets/logos/sponsors/FIUSCIS.svg
  src/assets/logos/sponsors/Google.svg
  src/assets/logos/sponsors/Lyft.svg
  src/assets/logos/sponsors/MuscleMilk.svg
  src/assets/logos/sponsors/Rockstar.svg
  src/assets/logos/sponsors/Stickermule.svg
  src/assets/logos/sponsors/Taxfyle.svg
  src/assets/logos/sponsors/Twilio.svg
  src/config/data/sponsors.json
  src/pages/landing/supporters/index.jsx
Labels: enhancement

#35 removed Kovens center from descriptions
  src/config/data/faq.js
  src/pages/landing/main/index.jsx
Labels: enhancement

#37 Wave3
  src/assets/logos/sponsors/Assurant.svg
  src/assets/logos/sponsors/Balsamiq.svg
  src/assets/logos/sponsors/CNB.svg
  src/assets/logos/sponsors/Carnival.svg
  src/assets/logos/sponsors/Citrix.svg
  src/assets/logos/sponsors/Cloudflare.svg
  src/assets/logos/sponsors/EA.svg
  src/assets/logos/sponsors/Farelogix.svg
  src/assets/logos/sponsors/Github.svg
  src/assets/logos/sponsors/Heroku.svg
  src/assets/logos/sponsors/Macys.svg
  src/assets/logos/sponsors/Matrix.svg
  src/assets/logos/sponsors/Mitre.svg
  src/assets/logos/sponsors/Nike.svg
  src/assets/logos/sponsors/Panthers.svg
  src/assets/logos/sponsors/Pepsi.svg
  src/assets/logos/sponsors/Redfin.svg
  src/assets/logos/sponsors/Ripplematch.svg
  src/assets/logos/sponsors/StateFarm.svg
  src/assets/logos/sponsors/Taylor.svg
  src/config/data/sponsors.json
  src/pages/landing/supporters/index.jsx
  src/pages/landing/supporters/styles.css
Labels: enhancement

#38 updated all sponsors
  src/config/data/sponsors.json
  src/pages/landing/supporters/index.jsx
Labels: enhancement

#39 removed unnecessary spaces
  src/pages/landing/supporters/index.jsx
Labels: bug
